name: Testes da Calculadora
run-name: ${{github.actor}} está testando o CI no GitHub
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configurando o Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Instalando a coverage
        run: pip install coverage
      - name: Cobertura dos testes
        run: | 
          coverage run -m unittest discover
          coverage report
          coverage html
      - name: Armazenar relatorio de cobertura
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: htmlcov
